---
- name: Install Docker on Servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository key (for Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (for Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker (for Ubuntu)
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service (for Ubuntu)
      systemd:
        name: docker
        enabled: yes
        state: started
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (for CentOS/RHEL)
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Docker (for CentOS/RHEL)
      package:
        name: docker-ce
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start and enable Docker service (for CentOS/RHEL)
      systemd:
        name: docker
        enabled: yes
        state: started
      when: ansible_os_family == 'RedHat'
